import {
  Company,
  Relationship,
  Contact,
  Opportunity,
  Interaction,
  Research,
  Intelligence,
  ProjectLink,
  ResearchCandidate,
  PriorityItem,
  PartnerGoal,
  ExecutiveKPIs,
} from '@/types';

export const mockPartnerGoal: PartnerGoal = {
  activeCount: 2,
  targetCount: 5,
  headline: "2 / 5 Active Partners",
  subtext: "Build your first five strategic partner relationships.",
};

export const mockKPIs: ExecutiveKPIs = {
  activePartners: 2,
  openOpportunities: 6,
  pipelineValueFormatted: "₹2.4 Cr",
  followupsDue: 3,
  staleRelationships: 2,
};

export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    name: "Northstar Interiors",
    domain: "northstardesign.co",
    type: "Interior Design",
    city: "Mumbai",
    employeeCount: "25-50",
    website: "https://northstardesign.co",
    logoInitials: "NI",
    yearEstablished: 2017,
  },
  {
    id: "comp-2",
    name: "Studio Arc",
    domain: "studioarc.in",
    type: "Architecture",
    city: "Bengaluru",
    employeeCount: "50-100",
    website: "https://studioarc.in",
    logoInitials: "SA",
    yearEstablished: 2014,
  },
  {
    id: "comp-3",
    name: "BuildLab Design",
    domain: "buildlab.io",
    type: "Turnkey D&B",
    city: "Delhi NCR",
    employeeCount: "10-25",
    website: "https://buildlab.io",
    logoInitials: "BL",
    yearEstablished: 2019,
  },
  {
    id: "comp-4",
    name: "Form & Function",
    domain: "formfunction.design",
    type: "Interior Design",
    city: "Hyderabad",
    employeeCount: "15-30",
    website: "https://formfunction.design",
    logoInitials: "FF",
    yearEstablished: 2016,
  },
  {
    id: "comp-5",
    name: "UrbanCraft Architects",
    domain: "urbancraft.co.in",
    type: "Architecture",
    city: "Pune",
    employeeCount: "30-75",
    website: "https://urbancraft.co.in",
    logoInitials: "UC",
    yearEstablished: 2012,
  },
];

export const mockRelationships: Relationship[] = [
  {
    id: "rel-1",
    companyId: "comp-1",
    status: "Active Partner",
    temperature: "Warm",
    owner: "Ravi",
    firstContactDate: "2025-11-10",
    lastMeaningfulInteractionDate: "2026-08-27",
    daysInactive: 21,
    nextAction: "Follow up regarding upcoming luxury residential pipeline",
    nextActionDate: "2026-09-18",
    partnerSince: "2026-02-15",
    relationshipNotes: "Key partner for premium interior execution. Completed initial pilot project with high satisfaction.",
    servicesDiscussed: ["Bespoke Joinery", "Turnkey Fitout", "Acoustics"],
  },
  {
    id: "rel-2",
    companyId: "comp-2",
    status: "Opportunity",
    temperature: "Hot",
    owner: "Ravi",
    firstContactDate: "2026-01-14",
    lastMeaningfulInteractionDate: "2026-09-12",
    daysInactive: 5,
    nextAction: "Review commercial proposal terms and schedule closing meeting",
    nextActionDate: "2026-09-19",
    relationshipNotes: "Leading architecture firm in South India. High potential for recurring commercial projects.",
    servicesDiscussed: ["Architectural Millwork", "Custom Lighting Integration"],
  },
  {
    id: "rel-3",
    companyId: "comp-3",
    status: "Active Partner",
    temperature: "Hot",
    owner: "Ravi",
    firstContactDate: "2025-09-01",
    lastMeaningfulInteractionDate: "2026-09-15",
    daysInactive: 2,
    nextAction: "Prepare design coordination kickoff for North Plaza project",
    nextActionDate: "2026-09-22",
    partnerSince: "2025-12-01",
    relationshipNotes: "Strategic Design-Build partner in NCR. Fast execution cadence and reliable project volume.",
    servicesDiscussed: ["Full Turnkey Execution", "MEP Integration"],
  },
  {
    id: "rel-4",
    companyId: "comp-4",
    status: "Meeting",
    temperature: "Warm",
    owner: "Ravi",
    firstContactDate: "2026-04-18",
    lastMeaningfulInteractionDate: "2026-09-16",
    daysInactive: 1,
    nextAction: "Conduct exploratory workshop with principal architects",
    nextActionDate: "2026-09-18",
    relationshipNotes: "Boutique high-end workspace designers looking for reliable engineering partners.",
    servicesDiscussed: ["Modular Joinery", "Glass Partitions"],
  },
  {
    id: "rel-5",
    companyId: "comp-5",
    status: "Prospect",
    temperature: "Stale",
    owner: "Ravi",
    firstContactDate: "2025-08-20",
    lastMeaningfulInteractionDate: "2026-07-30",
    daysInactive: 49,
    nextAction: "Re-engage leadership with updated portfolio case studies",
    nextActionDate: "2026-09-25",
    relationshipNotes: "Large architectural consultancy. Relationship slowed down during Q2 restructure.",
    servicesDiscussed: ["Facade Detailing", "Custom Metalwork"],
  },
];

export const mockContacts: Contact[] = [
  {
    id: "cnt-1",
    companyId: "comp-1",
    name: "Ar. Priya Sharma",
    role: "Design Director & Founder",
    email: "priya@northstardesign.co",
    phone: "+91 98200 11223",
    isDecisionMaker: true,
  },
  {
    id: "cnt-2",
    companyId: "comp-1",
    name: "Vikram Mehta",
    role: "Head of Procurement",
    email: "vikram@northstardesign.co",
    phone: "+91 98200 44556",
    isDecisionMaker: false,
  },
  {
    id: "cnt-3",
    companyId: "comp-2",
    name: "Rajesh Iyer",
    role: "Managing Principal",
    email: "riyer@studioarc.in",
    phone: "+91 98450 33445",
    isDecisionMaker: true,
  },
  {
    id: "cnt-4",
    companyId: "comp-3",
    name: "Kabir Singh",
    role: "Director of Operations",
    email: "kabir@buildlab.io",
    phone: "+91 99100 88776",
    isDecisionMaker: true,
  },
  {
    id: "cnt-5",
    companyId: "comp-4",
    name: "Ananya Rao",
    role: "Partner & Principal Interior Architect",
    email: "ananya@formfunction.design",
    phone: "+91 97000 66554",
    isDecisionMaker: true,
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    companyId: "comp-2",
    title: "Bengaluru Tech Park - Phase 2 Commercial Interiors",
    stage: "Proposal",
    estimatedValueFormatted: "₹85 Lac",
    estimatedValueAmount: 8500000,
    nextAction: "Submit refined BOQ and timeline schedule",
    nextActionDate: "2026-09-19",
    createdDate: "2026-08-10",
  },
  {
    id: "opp-2",
    companyId: "comp-4",
    title: "Jubilee Hills Flagship Residence Fitout",
    stage: "Discovery",
    estimatedValueFormatted: "₹45 Lac",
    estimatedValueAmount: 4500000,
    nextAction: "Present material sample board in exploratory meeting",
    nextActionDate: "2026-09-18",
    createdDate: "2026-09-01",
  },
  {
    id: "opp-3",
    companyId: "comp-1",
    title: "Worli Penthouse Joinery Package",
    stage: "Negotiation",
    estimatedValueFormatted: "₹60 Lac",
    estimatedValueAmount: 6000000,
    nextAction: "Finalize payment milestones with procurement head",
    nextActionDate: "2026-09-21",
    createdDate: "2026-07-28",
  },
  {
    id: "opp-4",
    companyId: "comp-3",
    title: "Cyber City Corporate Headquarters",
    stage: "Qualification",
    estimatedValueFormatted: "₹50 Lac",
    estimatedValueAmount: 5000000,
    nextAction: "Conduct technical feasibility review",
    nextActionDate: "2026-09-24",
    createdDate: "2026-09-14",
  },
];

export const mockInteractions: Interaction[] = [
  {
    id: "int-1",
    companyId: "comp-1",
    contactId: "cnt-1",
    contactName: "Ar. Priya Sharma",
    date: "2026-08-27",
    channel: "Meeting",
    summary: "Reviewed upcoming Q4 luxury residential portfolio and discussed joinery standardization.",
    whatTheyNeeded: "Reliable precision joinery manufacturing with guaranteed delivery timelines.",
    whatWeLearned: "They are expanding into Goa luxury villas and need an exclusive execution partner.",
    nextAction: "Follow up regarding upcoming Goa villa project pipeline",
    nextActionDate: "2026-09-18",
    noFurtherActionRequired: false,
  },
  {
    id: "int-2",
    companyId: "comp-2",
    contactId: "cnt-3",
    contactName: "Rajesh Iyer",
    date: "2026-09-12",
    channel: "Call",
    summary: "Detailed review of Tech Park Phase 2 proposal scope and technical specifications.",
    whatTheyNeeded: "Clarification on acoustics ceiling integration and custom lighting tracks.",
    whatWeLearned: "Client deadline is tight; quick turnaround on revised proposal will secure sole partner status.",
    nextAction: "Review commercial proposal terms and schedule closing meeting",
    nextActionDate: "2026-09-19",
    noFurtherActionRequired: false,
  },
  {
    id: "int-3",
    companyId: "comp-4",
    contactId: "cnt-5",
    contactName: "Ananya Rao",
    date: "2026-09-16",
    channel: "WhatsApp",
    summary: "Confirmed agenda for exploratory meeting regarding Jubilee Hills Residence.",
    whatTheyNeeded: "Material finishes catalog and engineered wood samples.",
    whatWeLearned: "They prioritize sustainable low-VOC materials and German hardware.",
    nextAction: "Conduct exploratory workshop with principal architects",
    nextActionDate: "2026-09-18",
    noFurtherActionRequired: false,
  },
];

export const mockResearchCandidates: ResearchCandidate[] = [
  {
    id: "rc-1",
    name: "Apex Workspaces",
    industrySegment: "Turnkey D&B",
    city: "Mumbai",
    source: "Architectural Digest India 2026 List",
    aiScore: 92,
    verificationStatus: "VERIFIED",
    discoveredDate: "2026-09-14",
    summary: "Fast-growing commercial interior studio delivering tech office headquarters across Western India.",
    keyContactsIdentified: 3,
  },
  {
    id: "rc-2",
    name: "Vanguard Design Lab",
    industrySegment: "Architecture",
    city: "Delhi NCR",
    source: "AI Web Signal Analysis",
    aiScore: 88,
    verificationStatus: "UNVERIFIED",
    discoveredDate: "2026-09-15",
    summary: "Boutique sustainable architecture firm expanding into luxury hospitality interiors.",
    keyContactsIdentified: 2,
  },
  {
    id: "rc-3",
    name: "Modus Spatial",
    industrySegment: "Interior Design",
    city: "Hyderabad",
    source: "Industry Network Signal",
    aiScore: 79,
    verificationStatus: "UNVERIFIED",
    discoveredDate: "2026-09-16",
    summary: "Specialist residential interior design studio with high-net-worth client focus.",
    keyContactsIdentified: 1,
  },
];

export const mockPriorities: PriorityItem[] = [
  {
    id: "prio-1",
    companyId: "comp-1",
    companyName: "Northstar Interiors",
    reason: "21 days since last meaningful interaction. Follow-up due for upcoming Q4 pipeline.",
    priority: "High",
    suggestedAction: "Follow up on upcoming project pipeline",
    dueText: "Due Today",
  },
  {
    id: "prio-2",
    companyId: "comp-2",
    companyName: "Studio Arc",
    reason: "Proposal submitted for Tech Park Phase 2 (₹85 Lac). Awaiting response.",
    priority: "High",
    suggestedAction: "Schedule closing conversation",
    dueText: "Tomorrow",
  },
  {
    id: "prio-3",
    companyId: "comp-4",
    companyName: "Form & Function",
    reason: "Exploratory workshop scheduled with principal architect Ananya Rao.",
    priority: "Medium",
    suggestedAction: "Prepare meeting materials & samples",
    dueText: "Today, 4:00 PM",
  },
];

export const mockResearch: Record<string, Research> = {
  "comp-1": {
    id: "res-1",
    companyId: "comp-1",
    marketSegment: "High-End Residential & Luxury Hospitality",
    strengths: ["Strong brand reputation", "HNW client base", "Focus on bespoke aesthetic"],
    growthSignals: ["Opening new Studio in Goa", "Increased project size by 40% year-on-year"],
    sources: [
      { title: "Northstar Design Portfolio 2026", url: "https://northstardesign.co/portfolio" },
      { title: "Architectural Digest Profile", url: "https://adindia.com/northstar" },
    ],
    lastUpdated: "2026-09-10",
  },
  "comp-2": {
    id: "res-2",
    companyId: "comp-2",
    marketSegment: "Commercial IT Parks & Corporate HQs",
    strengths: ["Large-scale master planning", "Institutional developer ties", "Strong engineering team"],
    growthSignals: ["Secured 200,000 sq ft office park master contract", "Expanding into Hyderabad"],
    sources: [
      { title: "Studio Arc Official Website", url: "https://studioarc.in" },
      { title: "Economic Times Property Report", url: "https://economictimes.indiana/studio-arc" },
    ],
    lastUpdated: "2026-09-12",
  },
};

export const mockIntelligence: Record<string, Intelligence> = {
  "comp-1": {
    id: "intel-1",
    companyId: "comp-1",
    healthScore: 85,
    recommendation: "Proactively offer turn-key joinery sample kits tailored for their upcoming Goa luxury villa projects.",
    nurtureCadence: "Bi-weekly founder touchpoint",
    growthPotential: "Exceptional",
  },
  "comp-2": {
    id: "intel-2",
    companyId: "comp-2",
    healthScore: 92,
    recommendation: "Focus conversation on guaranteed delivery timelines for Tech Park Phase 2 to close the proposal quickly.",
    nurtureCadence: "Weekly active deal touchpoint",
    growthPotential: "High",
  },
};

export const mockProjectLinks: Record<string, ProjectLink[]> = {
  "comp-1": [
    {
      id: "pl-1",
      companyId: "comp-1",
      projectHubId: "HUB-PRJ-2025-089",
      projectName: "Bandra Seafront Luxury Residence",
      status: "Completed",
      valueFormatted: "₹38 Lac",
      completedDate: "2026-02-10",
    },
  ],
  "comp-3": [
    {
      id: "pl-2",
      companyId: "comp-3",
      projectHubId: "HUB-PRJ-2025-042",
      projectName: "Gurugram FinTech Office Fitout",
      status: "Completed",
      valueFormatted: "₹65 Lac",
      completedDate: "2025-11-28",
    },
  ],
};
